name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: "install boost"
      run: sudo apt-get -y install libboost-dev
    - name: "run CMake"
      run: cmake -S . build
    - name: "build project"
      run: cmake --build build --target all -j4
